config/routes.rb
Rails.application.routes.draw do
  resources :patients do
    resources :encounters
  end
  root "patients#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/encounter.rb
class Encounter < ApplicationRecord
  belongs_to :patient
  validates :patient_id, :visit_no, :admitted_at, :presence => true
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :encounters, dependent: :destroy
  validates :first_name, :middle_name, :mrn, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController
  before_action :set_patient
  before_action :set_encounter, only: [:show, :edit, :update, :destroy]

  # GET /encounters
  # GET /encounters.json
  def index
    @encounters = Encounter.all
  end

  # GET /encounters/1
  # GET /encounters/1.json
  def show
  end

  # GET /encounters/new
  def new
    @encounter = Encounter.new
  end

  # GET /encounters/1/edit
  def edit
  end

  # POST /encounters
  # POST /encounters.json
  def create
    @encounter = Encounter.new(encounter_params)
    respond_to do |format|
      validated = true

      if not @encounter.discharged_at.nil? and @encounter.discharged_at < @encounter.admitted_at
        validated = false
        @encounter.errors.add(:discharged_at, "cannot be lower than Admitted at")
      end

      if validated and @encounter.save
        format.html { redirect_to patient_url(:id => @patient.id), notice: 'Encounter was successfully created.' }
        format.json { render :show, status: :created, location: @encounter }
      else
        format.html { render :new }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /encounters/1
  # PATCH/PUT /encounters/1.json
  def update
    respond_to do |format|
      validated = true
      discharged_at_date = nil

      admitted_at_date = DateTime.new(encounter_params[:"admitted_at(1i)"].to_i,
                                      encounter_params[:"admitted_at(2i)"].to_i,
                                      encounter_params[:"admitted_at(3i)"].to_i,
                                      encounter_params[:"admitted_at(4i)"].to_i,
                                      encounter_params[:"admitted_at(5i)"].to_i)

      if not encounter_params[:"discharged_at(1i)"].empty? and
          not encounter_params[:"discharged_at(2i)"].empty? and
          not encounter_params[:"discharged_at(3i)"].empty? and
          not encounter_params[:"discharged_at(4i)"].empty? and
          not encounter_params[:"discharged_at(5i)"].empty?
        discharged_at_date = DateTime.new(encounter_params[:"discharged_at(1i)"].to_i,
                                        encounter_params[:"discharged_at(2i)"].to_i,
                                        encounter_params[:"discharged_at(3i)"].to_i,
                                        encounter_params[:"discharged_at(4i)"].to_i,
                                        encounter_params[:"discharged_at(5i)"].to_i)
      end

      if discharged_at_date and discharged_at_date < admitted_at_date
        validated = false
        @encounter.errors.add(:discharged_at, "cannot be lower than Admitted at")
      end

      if validated and @encounter.update(encounter_params)
        format.html { redirect_to patient_url(:id => @patient.id), notice: 'Encounter was successfully updated.' }
        format.json { render :show, status: :ok, location: @encounter }
      else
        format.html { render :edit }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end

    end
  end

  # DELETE /encounters/1
  # DELETE /encounters/1.json
  def destroy
    @encounter.destroy
    respond_to do |format|
      format.html { redirect_to patient_url(:id => @patient.id), notice: 'Encounter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:patient_id])
    end

    def set_encounter
      @encounter = Encounter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def encounter_params
      params.require(:encounter).permit(:visit_no, :admitted_at, :discharged_at, :location, :room, :bed).merge(:patient_id => params[:patient_id])
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @encounters = Encounter.where(patient_id: @patient.id).all
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|

      validated = true
      if @patient.first_name =~ /\d/
        validated = false
        @patient.errors.add(:first_name, "cannot have numbers in it")
      end

      if @patient.middle_name =~ /\d/
        validated = false
        @patient.errors.add(:middle_name, "cannot have numbers in it")
      end

      if @patient.last_name and @patient.last_name =~ /\d/
        validated = false
        @patient.errors.add(:last_name, "cannot have numbers in it")
      end

      if not patient_params[:weight].empty? and patient_params[:weight].count("a-zA-Z") > 0
        validated = false
        @patient.errors.add(:weight, "has to be a number")
      end

      if not patient_params[:height].empty? and patient_params[:height].count("a-zA-Z") > 0
        validated = false
        @patient.errors.add(:height, "has to be a number")
      end

      if validated and @patient.save
        format.html { redirect_to patients_url, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end


    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      validated = true

      if patient_params[:first_name] =~ /\d/
        validated = false
        @patient.errors.add(:first_name, "cannot have numbers in it")
      end

      if patient_params[:middle_name] =~ /\d/
        validated = false
        @patient.errors.add(:middle_name, "cannot have numbers in it")
      end

      if not patient_params[:last_name].empty? and patient_params[:last_name] =~ /\d/
        validated = false
        @patient.errors.add(:last_name, "cannot have numbers in it")
      end

      if not patient_params[:weight].empty? and patient_params[:weight].count("a-zA-Z") > 0
        validated = false
        @patient.errors.add(:weight, "has to be a number")
      end

      if not patient_params[:height].empty? and patient_params[:height].count("a-zA-Z") > 0
        validated = false
        @patient.errors.add(:height, "has to be a number")
      end

      if validated and @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end

    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :middle_name, :last_name, :weight, :height, :mrn)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/encounters_helper.rb
module EncountersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/encounters/_form.html.erb
<%= form_with(model: [@patient, encounter], local: true) do |form| %>
  <% if encounter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(encounter.errors.count, "error") %> prohibited this encounter from being saved:</h2>

      <ul>
      <% encounter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :visit_no %>
    <%= form.text_field :visit_no, id: :encounter_visit_no %>
  </div>

  <div class="field">
    <%= form.label :admitted_at %>
    <%= form.datetime_select :admitted_at, id: :encounter_admitted_at %>
  </div>

  <div class="field">
    <%= form.label :discharged_at %>
    <%= form.datetime_select :discharged_at, id: :encounter_discharged_at, :include_blank => true %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :encounter_location %>
  </div>

  <div class="field">
    <%= form.label :room %>
    <%= form.text_field :room, id: :encounter_room %>
  </div>

  <div class="field">
    <%= form.label :bed %>
    <%= form.text_field :bed, id: :encounter_bed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/encounters/edit.html.erb
<h1>Editing Encounter</h1>

<%= render 'form', patient: @patient, encounter: @encounter %>

<%= link_to 'Back', patient_path(@patient) %>

app/views/encounters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Encounters</h1>

<table>
  <thead>
    <tr>
      <th>Visit no</th>
      <th>Admitted at</th>
      <th>Discharged at</th>
      <th>Location</th>
      <th>Room</th>
      <th>Bed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @encounters.each do |encounter| %>
      <tr>
        <td><%= encounter.visit_no %></td>
        <td><%= encounter.admitted_at %></td>
        <td><%= encounter.discharged_at %></td>
        <td><%= encounter.location %></td>
        <td><%= encounter.room %></td>
        <td><%= encounter.bed %></td>
        <td><%= link_to 'Show', patient_encounter_path(@patient, encounter) %></td>
        <td><%= link_to 'Edit', edit_patient_encounter_path(@patient, encounter) %></td>

        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Encounter', new_patient_encounter_path %>

app/views/encounters/new.html.erb
<h1>New Encounter</h1>

<%= render 'form', patient: @patient, encounter: @encounter %>

<%= link_to 'Back', patient_path(@patient) %>

app/views/encounters/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Encounter Details</h1>

<p>
  <strong>Visit no:</strong>
  <%= @encounter.visit_no %>
</p>

<p>
  <strong>Admitted at:</strong>
  <%= @encounter.admitted_at %>
</p>

<p>
  <strong>Discharged at:</strong>
  <%= @encounter.discharged_at %>
</p>

<p>
  <strong>Location:</strong>
  <%= @encounter.location %>
</p>

<p>
  <strong>Room:</strong>
  <%= @encounter.room %>
</p>

<p>
  <strong>Bed:</strong>
  <%= @encounter.bed %>
</p>


<%= link_to 'Back', patient_path(@patient) %>

<%= button_to 'Edit', edit_patient_encounter_path(@patient, @encounter), method: :get %>

<%= link_to 'Destroy', patient_encounter_path(@patient, @encounter), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diagnoseme</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :patient_first_name %>
  </div>

    <div class="field">
      <%= form.label :middle_name %>
      <%= form.text_field :middle_name, id: :patient_middle_name %>
    </div>

    <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :patient_last_name %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight, id: :patient_weight %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.text_field :height, id: :patient_height %>
  </div>

  <div class="field">
    <%= form.label :mrn %>
    <%= form.text_field :mrn, id: :patient_mrn %>
  </div>

  <div class="actions">
    <%= form.submit "Submit" %>
  </div>

<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients</h1>

<%= button_to "New Patient", new_patient_path, :method => :get %>

<br>

<table border="1">
  <thead>
    <tr>
      <th>MRN</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.mrn %></td>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= link_to 'Show', patient %> <%= link_to 'Edit', edit_patient_path(patient) %> <%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= button_to 'Cancel', patients_path, method: :get %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Patient's Details</h1>

<p>
  <strong>MRN:</strong>
  <%= @patient.mrn %>
</p>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @patient.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @patient.last_name %>
</p>

<p>
  <strong>Weight (in kg):</strong>
  <%= @patient.weight %>
</p>

<p>
  <strong>Height (in cm):</strong>
  <%= @patient.height %>
</p>

<h2>Encounters</h2>

<%= button_to "Add Encounter", new_patient_encounter_path(@patient), :method => :get %>

<br>

<table border="1">
  <thead>
  <tr>
    <th>Visit Number</th>
    <th>Admitted At</th>
    <th>Discharged At</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @encounters.each do |encounter| %>
      <tr>
        <td><%= encounter.visit_no %></td>
        <td><%= encounter.admitted_at %></td>
        <td><%= encounter.discharged_at %></td>
        <td><%= link_to 'Show', patient_encounter_path(@patient, encounter) %> <%= link_to 'Edit', edit_patient_encounter_path(@patient, encounter) %> <%= link_to 'Destroy', patient_encounter_path(@patient, encounter), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Back', patients_path, method: :get %>